spring:
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
  datasource:
    url: jdbc:postgresql://localhost:5432/skill_exchange
    username: arunkumaria
    password: 
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
